terraform {
  required_providers {
    statuspal = {
      source = "registry.terraform.io/statuspal/statuspal"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }

  required_version = ">= 1.4.0"
}

provider "statuspal" {
  api_key = var.statuspal_api_key
  region  = "US"
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

variable "statuspal_api_key" {
  sensitive = true
}

variable "cloudflare_api_token" {
  sensitive = true
}

variable "cloudflare_zone_id" {}

variable "org_id" {}

# Step 1 — Create the status page with domain_config.
# The CNAME routing record is available immediately in validation_records["cname"].
resource "statuspal_status_page" "main" {
  organization_id = var.org_id
  status_page = {
    name      = "Acme Status"
    url       = "https://status.acme.com"
    time_zone = "UTC"
    subdomain = "acme"

    domain_config = {
      provider = "cloudflare"
      domain   = "status.acme.com"
    }
  }
}

# Step 2 — CNAME record to route the custom domain to StatusPal.
resource "cloudflare_record" "cname" {
  zone_id = var.cloudflare_zone_id
  name    = statuspal_status_page.main.status_page.domain_config.validation_records["cname"].name
  type    = "CNAME"
  content = statuspal_status_page.main.status_page.domain_config.validation_records["cname"].value
  proxied = false
  ttl     = 120
}

# Step 3 — Wait for the SSL certificate TXT challenge to appear.
# This record is only generated by Cloudflare after the CNAME is in DNS.
resource "statuspal_domain_ssl_records" "main" {
  organization_id       = var.org_id
  status_page_subdomain = statuspal_status_page.main.status_page.subdomain
  timeout_seconds       = 300

  depends_on = [cloudflare_record.cname]
}

# Step 4 — TXT record for SSL certificate issuance.
resource "cloudflare_record" "txt" {
  zone_id = var.cloudflare_zone_id
  name    = statuspal_domain_ssl_records.main.certificate_txt_name
  type    = "TXT"
  content = statuspal_domain_ssl_records.main.certificate_txt_value
  ttl     = 120
}

# Step 5 — Wait until the custom domain is fully active.
resource "statuspal_custom_domain_validation" "main" {
  organization_id       = var.org_id
  status_page_subdomain = statuspal_status_page.main.status_page.subdomain
  timeout_seconds       = 600

  depends_on = [cloudflare_record.txt]
}

output "domain_status" {
  value = statuspal_status_page.main.status_page.domain_config.status
}
