package provider

import (
	"log"
	"net/http"
	"net/http/httptest"
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccStatusPagesDataSource(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("/orgs/1/status_pages", func(w http.ResponseWriter, r *http.Request) {
		// Mock response for data source
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write([]byte(`{
			"links": {
				"next": null,
				"prev": null
			},
			"meta": {
				"total_count": 3
			},
			"status_pages": [
				{
					"theme_selected": "default",
					"scheduled_maintenance_days": 7,
					"display_uptime_graph": true,
					"inserted_at": "2024-04-15T11:20:35",
					"updated_at": "2024-04-20T11:22:32",
					"header_fg_color": "ffffff",
					"history_limit_days": 90,
					"head_code": null,
					"domain": null,
					"support_email": null,
					"locked_when_maintenance": false,
					"organization_id": 1,
					"custom_footer": null,
					"custom_incident_types_enabled": false,
					"slack_subscriptions_enabled": null,
					"date_format": null,
					"maintenance_notification_hours": 6,
					"subdomain": "example-com-3",
					"twitter_public_screen_name": null,
					"header_logo_text": "Example Status",
					"member_restricted": null,
					"url": "example.com",
					"status_ok_color": "48CBA5",
					"uptime_graph_days": 90,
					"subscribers_enabled": true,
					"display_about": true,
					"translations": {
						"en": {
							"header_logo_text": "",
							"public_company_name": "Public company name EN"
						},
						"fr": {
							"header_logo_text": "",
							"public_company_name": "Public company name FR"
						}
					},
					"tweet_by_default": false,
					"display_calendar": true,
					"email_templates_enabled": null,
					"google_calendar_enabled": false,
					"link_color": "0c91c3",
					"email_layout_template": null,
					"name": "Example EDITED",
					"status_major_color": "e75a53",
					"custom_header": null,
					"date_format_enforce_everywhere": false,
					"time_format": null,
					"header_bg_color1": "009688",
					"incident_link_color": null,
					"bg_image": null,
					"custom_css": null,
					"current_incidents_position": "below_services",
					"custom_js": null,
					"minor_notification_hours": 6,
					"mattermost_notifications_enabled": false,
					"info_notices_enabled": true,
					"captcha_enabled": true,
					"about": null,
					"google_chat_notifications_enabled": false,
					"discord_notifications_enabled": false,
					"theme_configs": null,
					"status_minor_color": "FFA500",
					"tweeting_enabled": true,
					"sms_notifications_enabled": null,
					"notify_by_default": false,
					"hide_watermark": false,
					"custom_domain_enabled": false,
					"enable_auto_translations": false,
					"restricted_ips": null,
					"feed_enabled": true,
					"header_bg_color2": "0c91c3",
					"public_company_name": null,
					"notification_email": null,
					"email_notification_template": null,
					"teams_notifications_enabled": false,
					"status_maintenance_color": "5378c1",
					"email_confirmation_template": null,
					"time_zone": "Europe/Belgrade",
					"calendar_enabled": false,
					"major_notification_hours": 3,
					"incident_header_color": "009688",
					"reply_to_email": null,
					"noindex": false
				},
				{
					"theme_selected": "default",
					"scheduled_maintenance_days": 7,
					"display_uptime_graph": true,
					"inserted_at": "2024-04-15T11:20:35",
					"updated_at": "2024-04-20T11:22:32",
					"header_fg_color": "ffffff",
					"history_limit_days": null,
					"head_code": null,
					"domain": "status.acme.corp",
					"support_email": null,
					"locked_when_maintenance": false,
					"organization_id": 1,
					"custom_footer": null,
					"custom_incident_types_enabled": true,
					"slack_subscriptions_enabled": true,
					"date_format": null,
					"maintenance_notification_hours": 6,
					"subdomain": "pontsystems-eu-hu",
					"twitter_public_screen_name": null,
					"header_logo_text": null,
					"member_restricted": true,
					"url": "www.pontsystems.eu/hu",
					"status_ok_color": "C0B0CB",
					"uptime_graph_days": 90,
					"subscribers_enabled": true,
					"display_about": true,
					"translations": {
						"en": {
							"header_logo_text": "",
							"public_company_name": "Public company name EN"
						},
						"fr": {
							"header_logo_text": "",
							"public_company_name": "Public company name FR"
						}
					},
					"tweet_by_default": false,
					"display_calendar": true,
					"email_templates_enabled": true,
					"google_calendar_enabled": true,
					"link_color": "0c91c3",
					"email_layout_template": "<html>\r\n  <head>\r\n    <meta name=\"viewport\" content=\"width=device-width\" />\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n\r\n    <style>\r\n      /* -------------------------------------\r\n          GLOBAL\r\n          A very basic CSS reset\r\n      ------------------------------------- */\r\n      * {\r\n        margin: 0;\r\n        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\r\n        box-sizing: border-box;\r\n        font-size: 14px;\r\n      }\r\n\r\n      img {\r\n        max-width: 100%;\r\n      }\r\n\r\n      body {\r\n        -webkit-font-smoothing: antialiased;\r\n        -webkit-text-size-adjust: none;\r\n        width: 100% !important;\r\n        height: 100%;\r\n        line-height: 1.6em;\r\n        /* 1.6em * 14px = 22.4px, use px to get airier line-height also in Thunderbird, and Yahoo!, Outlook.com, AOL webmail clients */\r\n        /*line-height: 22px;*/\r\n      }\r\n\r\n      /* Let's make sure all tables have defaults */\r\n      table td {\r\n        vertical-align: top;\r\n      }\r\n\r\n      /* -------------------------------------\r\n          BODY & CONTAINER\r\n      ------------------------------------- */\r\n      body {\r\n        background-color: #f6f6f6;\r\n      }\r\n\r\n      .body-wrap {\r\n        background-color: #f6f6f6;\r\n        width: 100%;\r\n      }\r\n\r\n      .container {\r\n        display: block !important;\r\n        max-width: 600px !important;\r\n        margin: 0 auto !important;\r\n        /* makes it centered */\r\n        clear: both !important;\r\n      }\r\n\r\n      .content {\r\n        max-width: 600px;\r\n        margin: 0 auto;\r\n        display: block;\r\n        padding: 20px;\r\n      }\r\n\r\n      /* -------------------------------------\r\n          HEADER, FOOTER, MAIN\r\n      ------------------------------------- */\r\n      .main {\r\n        background-color: #fff;\r\n        border: 1px solid #e9e9e9;\r\n        border-radius: 3px;\r\n      }\r\n\r\n      .content-wrap {\r\n        padding: 20px;\r\n      }\r\n\r\n      .content-block {\r\n        /* padding: 0 0 20px; */\r\n      }\r\n\r\n      .header {\r\n        width: 100%;\r\n        padding-top: 20px;\r\n        text-align: center;\r\n      }\r\n\r\n      .logo {\r\n        max-width: 300px;\r\n      }\r\n\r\n      .footer {\r\n        width: 100%;\r\n        clear: both;\r\n        color: #999;\r\n        padding: 20px;\r\n      }\r\n\r\n      .footer p, .footer a, .footer td {\r\n        color: #999;\r\n        font-size: 12px;\r\n      }\r\n\r\n      /* -------------------------------------\r\n          TYPOGRAPHY\r\n      ------------------------------------- */\r\n      h1, h2, h3 {\r\n        font-family: \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\r\n        color: #000;\r\n        margin: 40px 0 0;\r\n        line-height: 1.2em;\r\n        font-weight: 400;\r\n      }\r\n\r\n      h1 {\r\n        font-size: 32px;\r\n        font-weight: 500;\r\n        /* 1.2em * 32px = 38.4px, use px to get airier line-height also in Thunderbird, and Yahoo!, Outlook.com, AOL webmail clients */\r\n        /*line-height: 38px;*/\r\n      }\r\n\r\n      h2 {\r\n        font-size: 24px;\r\n        /* 1.2em * 24px = 28.8px, use px to get airier line-height also in Thunderbird, and Yahoo!, Outlook.com, AOL webmail clients */\r\n        /*line-height: 29px;*/\r\n      }\r\n\r\n      h3 {\r\n        font-size: 18px;\r\n        /* 1.2em * 18px = 21.6px, use px to get airier line-height also in Thunderbird, and Yahoo!, Outlook.com, AOL webmail clients */\r\n        /*line-height: 22px;*/\r\n      }\r\n\r\n      h4 {\r\n        font-size: 14px;\r\n        font-weight: 600;\r\n      }\r\n\r\n      p, ul, ol {\r\n        margin-bottom: 10px;\r\n        font-weight: normal;\r\n      }\r\n\r\n      p li, ul li, ol li {\r\n        margin-left: 5px;\r\n        list-style-position: inside;\r\n      }\r\n\r\n      /* -------------------------------------\r\n          LINKS & BUTTONS\r\n      ------------------------------------- */\r\n      a {\r\n        color: #000000;\r\n        text-decoration: underline;\r\n\t\tfont-weight: bold;\r\n      }\r\n\r\n      .btn-primary {\r\n        text-decoration: none;\r\n        color: #FFF;\r\n        background-color: #348eda;\r\n        border: solid #348eda;\r\n        border-width: 10px 20px;\r\n        line-height: 2em;\r\n        /* 2em * 14px = 28px, use px to get airier line-height also in Thunderbird, and Yahoo!, Outlook.com, AOL webmail clients */\r\n        /*line-height: 28px;*/\r\n        font-weight: bold;\r\n        text-align: center;\r\n        cursor: pointer;\r\n        display: inline-block;\r\n        border-radius: 5px;\r\n        text-transform: capitalize;\r\n      }\r\n\r\n      /* -------------------------------------\r\n          OTHER STYLES THAT MIGHT BE USEFUL\r\n      ------------------------------------- */\r\n      .last {\r\n        margin-bottom: 0;\r\n      }\r\n\r\n      .first {\r\n        margin-top: 0;\r\n      }\r\n\r\n      .aligncenter {\r\n        text-align: center;\r\n      }\r\n\r\n      .alignright {\r\n        text-align: right;\r\n      }\r\n\r\n      .alignleft {\r\n        text-align: left;\r\n      }\r\n\r\n      .clear {\r\n        clear: both;\r\n      }\r\n\r\n      /* -------------------------------------\r\n          ALERTS\r\n          Change the class depending on warning email, good email or bad email\r\n      ------------------------------------- */\r\n      .alert {\r\n        font-size: 16px;\r\n        color: #fff;\r\n        font-weight: 500;\r\n        padding: 20px;\r\n        text-align: center;\r\n        border-radius: 3px 3px 0 0;\r\n      }\r\n\t  \r\n      .alert a {\r\n        color: #fff;\r\n        text-decoration: none;\r\n        font-weight: 500;\r\n        font-size: 16px;\r\n      }\r\n\r\n      .alert.alert-warning {\r\n        background-color: #FFCC00;\r\n      }\r\n\r\n      .alert.alert-bad {\r\n        background-color: #D40511;\r\n      }\r\n\r\n      .alert.alert-good {\r\n        background-color: #68B90F;\r\n      }\r\n\r\n      .alert.alert-ok {\r\n        background-color: #2f81ff;\r\n      }\r\n\r\n  .alert.alert-info {\r\n    background-color: #48CBA5;\r\n  }\r\n\r\n      /* -------------------------------------\r\n          SERVICES\r\n      ------------------------------------- */\r\n\r\n      .services span.service{\r\n        display: inline-block;\r\n        white-space: nowrap;\r\n        border: 1px solid rgb(0, 0, 0);\r\n        padding: 3px 3px;\r\n        margin-bottom: 5px;\r\n        border-radius: 3px;\r\n      }\r\n\r\n      /* -------------------------------------\r\n          RESPONSIVE AND MOBILE FRIENDLY STYLES\r\n      ------------------------------------- */\r\n      @media only screen and (max-width: 640px) {\r\n        body {\r\n          padding: 0 !important;\r\n        }\r\n\r\n        h1, h2, h3, h4 {\r\n          font-weight: 800 !important;\r\n          margin: 20px 0 5px !important;\r\n        }\r\n\r\n        h1 {\r\n          font-size: 22px !important;\r\n        }\r\n\r\n        h2 {\r\n          font-size: 18px !important;\r\n        }\r\n\r\n        h3 {\r\n          font-size: 16px !important;\r\n        }\r\n\r\n        .container {\r\n          padding: 0 !important;\r\n          width: 100% !important;\r\n        }\r\n\r\n        .content {\r\n          padding: 0 !important;\r\n        }\r\n\r\n        .content-wrap {\r\n          padding: 10px !important;\r\n        }\r\n      }\r\n\r\n      /*# sourceMappingURL=styles.css.map */\r\n    </style>\r\n\r\n  </head>\r\n  <body itemscope itemtype=\"http://schema.org/EmailMessage\">\r\n    {{ content }}\r\n  </body>\r\n</html>",
					"name": "Test status page",
					"status_major_color": "e75a53",
					"custom_header": null,
					"date_format_enforce_everywhere": false,
					"time_format": "24-hour",
					"header_bg_color1": "009688",
					"incident_link_color": null,
					"bg_image": null,
					"custom_css": null,
					"current_incidents_position": "below_services",
					"custom_js": null,
					"minor_notification_hours": 6,
					"mattermost_notifications_enabled": true,
					"info_notices_enabled": true,
					"captcha_enabled": true,
					"about": null,
					"google_chat_notifications_enabled": false,
					"discord_notifications_enabled": false,
					"theme_configs": null,
					"status_minor_color": "A0FDFF",
					"tweeting_enabled": true,
					"sms_notifications_enabled": true,
					"notify_by_default": false,
					"hide_watermark": false,
					"custom_domain_enabled": false,
					"enable_auto_translations": false,
					"restricted_ips": null,
					"feed_enabled": true,
					"header_bg_color2": "0c91c3",
					"public_company_name": "Public company name FR",
					"notification_email": "daniel@dev.mg.edd.bz",
					"email_notification_template": "<table class=\"body-wrap\">\r\n\t<tr>\r\n\t\t<td></td>\r\n\t\t<td class=\"container\" width=\"630\">      \r\n                                                         \r\n\t\t\t<header class=\"nav\"  >\r\n\t\t\t\t<div class=\"container\"  style=\"background-color:#FFCC00; margin-top: 0;\">\r\n                                                                                     \r\n\t\t\t\t\t<a class=\"brand-name\" href=https://post-paket-deutschland.status.api.dhl.com>\r\n\t\t\t\t\t\t<img src=https://statuspal.eu/uploads/status_pages/logo/original/3642-dp-dhl-logo.png?v=63818963928>\r\n\t\t\t\t\t</a>\r\n                                                                                                                                                                              \r\n\t\t\t\t</div>\r\n\t\t\t</header>\r\n\t\t\r\n\t\t\t<br><br>\r\n\r\n\t\t\t<div class=\"content\" style=\"background-color:#FFFFFF;\"> \r\n\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n\t\t\t<table>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td width=\"90\"> <p class=\"alert alert-{{ incident.type_color_class }}\">[{{ activity.activity_type_name }}]</p></td>\r\n\t\t\t\t\t<td><b>  {{ incident.title }} </b></td>\r\n\t\t\t\t</tr>\r\n\t\t\t</table>\r\n        \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n\t\t\t<p class=\"content-block\">\r\n\t\t\t\t{{ maintenance_information }}\r\n\t\t\t\t<p>\r\n\t\t\t\t\t<b>{{ t_affected_services }} auf </b><a  href=https://test-status-pnp-de.statuspal.eu>IT Service Post Paket Deutschland (Test)</a>:\r\n\t\t\t\t\t<br><br>\r\n\t\t\t\t\t{{ services }}\r\n\t\t\t\t\t<br>\r\n\t\t\t\t</p>\r\n\r\n\t\t\t\t<p>\r\n\t\t\t\t\t{{ activity.description }}\r\n\t\t\t\t</p>\r\n                                                                                                                           \r\n\t\t\t\t<a href=\"{{ incident.url }}\" itemprop=\"url\">{{ t_open_report }}</a>\r\n\t\t\t\t<br><br>\r\n                                                                                     \r\n                 <p style=\"font-size:10px;\">                                                                                                                                                                                    \r\n\t\t\t\t\t<b style=\"font-size:9px;\">Anmerkung</b> - Wenn Sie Statusmeldungen nur für eine bestimmte Auswahl an IT Services erhalten möchten, können Sie Ihre Einstellungen über den Link <a href=\"{{ subscription.manage_url }}\"><b style=\"font-size:9px;\">Abonnement verwalten</b></a> ändern.\r\n\t\t\t\t\t<br>\r\n\t\t\t\t\tVielen Dank,<br>\r\n\t\t\t\t\tIhr Team Kundenintegrationsservice Post & Paket\r\n\t\t\t\t\t<br><br>\r\n\t\t\t\t\t<b style=\"font-size:9px;\">Note</b> - If you would like to get status messages just for a specific selection of IT services, you can change your preferences via the <a href=\"{{ subscription.manage_url }}?lang=en\"><b style=\"font-size:9px;\">Manage subscription</b></a> link.\r\n\t\t\t\t\t<br>\r\n\t\t\t\t\tThanks, <br> \r\n\t\t\t\t\tYour Customer Integration Team Post & Paket\r\n\t\t\t\t</p>\t\t\t\r\n\r\n\t\t\t\t<br>\r\n\t\t\t</p>\r\n                                                         \r\n\t\t\t<footer class=\"footer\">\r\n\t\t\t\t<center>\r\n\t\t\t\t\t<br>\r\n\t\t\t\t\t<a href=https://developer.dhl.com/imprint title=\"Imprint\">Imprint</a> &nbsp;\r\n\t\t\t\t\t<a href=https://developer.dhl.com/privacy-notice title=\"Privacy Notice\">Privacy Notice  </a> &nbsp;\r\n\t\t\t\t\t<a href=https://developer.dhl.com/terms-use>Terms of Use  </a>\r\n\t\t\t\t</center>                                                                                     \r\n\t\t\t\t<center>\r\n\t\t\t\t\t2024 © DHL International GmbH. All rights reserved.\r\n\t\t\t\t</center>\r\n\t\t\t</footer>\r\n                                                  \r\n        </td>\r\n                            \r\n        <td></td>\r\n\t\t\t  \r\n    </tr>\r\n</table>",
					"teams_notifications_enabled": false,
					"status_maintenance_color": "5378c1",
					"email_confirmation_template": null,
					"time_zone": "Europe/Belgrade",
					"calendar_enabled": false,
					"major_notification_hours": 3,
					"incident_header_color": "009688",
					"reply_to_email": null,
					"noindex": false
				},
				{
					"theme_selected": "default",
					"scheduled_maintenance_days": 7,
					"display_uptime_graph": true,
					"inserted_at": "2024-04-15T11:20:35",
					"updated_at": "2024-04-20T11:22:32",
					"header_fg_color": "ffffff",
					"history_limit_days": 90,
					"head_code": null,
					"domain": null,
					"support_email": null,
					"locked_when_maintenance": false,
					"organization_id": 1,
					"custom_footer": null,
					"custom_incident_types_enabled": false,
					"slack_subscriptions_enabled": false,
					"date_format": null,
					"maintenance_notification_hours": 6,
					"subdomain": "local-test-2",
					"twitter_public_screen_name": null,
					"header_logo_text": "Updated 3x from Terraform Status",
					"member_restricted": false,
					"url": "local.test",
					"status_ok_color": "48CBA5",
					"uptime_graph_days": 90,
					"subscribers_enabled": true,
					"display_about": false,
					"translations": {},
					"tweet_by_default": false,
					"display_calendar": true,
					"email_templates_enabled": false,
					"google_calendar_enabled": false,
					"link_color": "0c91c3",
					"email_layout_template": null,
					"name": "Updated 3x from Terraform",
					"status_major_color": "e75a53",
					"custom_header": null,
					"date_format_enforce_everywhere": false,
					"time_format": null,
					"header_bg_color1": "009688",
					"incident_link_color": null,
					"bg_image": null,
					"custom_css": null,
					"current_incidents_position": "below_services",
					"custom_js": null,
					"minor_notification_hours": 6,
					"mattermost_notifications_enabled": false,
					"info_notices_enabled": true,
					"captcha_enabled": true,
					"about": null,
					"google_chat_notifications_enabled": false,
					"discord_notifications_enabled": false,
					"theme_configs": {
						"header_bg_color1": "",
						"header_bg_color2": "",
						"header_fg_color": "",
						"incident_header_color": "",
						"link_color": "",
						"status_maintenance_color": "",
						"status_major_color": "",
						"status_minor_color": "",
						"status_ok_color": ""
					},
					"status_minor_color": "FFA500",
					"tweeting_enabled": true,
					"sms_notifications_enabled": false,
					"notify_by_default": false,
					"hide_watermark": false,
					"custom_domain_enabled": false,
					"enable_auto_translations": false,
					"restricted_ips": null,
					"feed_enabled": true,
					"header_bg_color2": "0c91c3",
					"public_company_name": null,
					"notification_email": null,
					"email_notification_template": null,
					"teams_notifications_enabled": false,
					"status_maintenance_color": "5378c1",
					"email_confirmation_template": null,
					"time_zone": "Europe/Budapest",
					"calendar_enabled": false,
					"major_notification_hours": 3,
					"incident_header_color": "009688",
					"reply_to_email": null,
					"noindex": false
				}
			]
		}`)); err != nil {
			log.Printf(`Error writing "/orgs/1/status_pages" response: %v`, err)
			return
		}
	})
	mockServer := httptest.NewServer(mux)
	defer mockServer.Close()
	providerConfig := providerConfig(&mockServer.URL)

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Missing required organization_id error testing
			{
				Config:      *providerConfig + `data "statuspal_status_pages" "test" {}`,
				ExpectError: regexp.MustCompile(`The argument "organization_id" is required, but no definition was found.`),
			},
			// Read testing
			{
				Config: *providerConfig + `data "statuspal_status_pages" "test" {
					organization_id = "1"
				}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "organization_id", "1"),
					// Verify number of status pages returned
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.#", "3"),
					// Verify the first status page to ensure all attributes are set
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.%", "73"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_selected", "default"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.scheduled_maintenance_days", "7"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.display_uptime_graph", "true"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.header_fg_color", "ffffff"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.history_limit_days", "90"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.head_code", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.domain", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.restricted_ips", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.support_email", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.locked_when_maintenance", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.custom_footer", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.custom_incident_types_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.slack_subscriptions_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.date_format", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.maintenance_notification_hours", "6"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.subdomain", "example-com-3"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.twitter_public_screen_name", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.header_logo_text", "Example Status"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.member_restricted", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.url", "example.com"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.status_ok_color", "48CBA5"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.uptime_graph_days", "90"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.subscribers_enabled", "true"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.display_about", "true"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.translations.%", "2"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.translations.en.%", "2"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.translations.en.header_logo_text", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.translations.en.public_company_name", "Public company name EN"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.translations.fr.%", "2"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.translations.fr.header_logo_text", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.translations.fr.public_company_name", "Public company name FR"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.tweet_by_default", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.display_calendar", "true"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.email_templates_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.google_calendar_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.link_color", "0c91c3"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.email_layout_template", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.name", "Example EDITED"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.status_major_color", "e75a53"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.custom_header", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.date_format_enforce_everywhere", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.time_format", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.header_bg_color1", "009688"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.incident_link_color", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.bg_image", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.custom_css", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.current_incidents_position", "below_services"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.custom_js", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.minor_notification_hours", "6"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.mattermost_notifications_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.info_notices_enabled", "true"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.captcha_enabled", "true"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.about", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.google_chat_notifications_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.discord_notifications_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.%", "9"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.link_color", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.header_bg_color1", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.header_bg_color2", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.header_fg_color", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.incident_header_color", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.status_ok_color", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.status_minor_color", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.status_major_color", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.theme_configs.status_maintenance_color", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.status_minor_color", "FFA500"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.tweeting_enabled", "true"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.sms_notifications_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.notify_by_default", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.hide_watermark", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.custom_domain_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.enable_auto_translations", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.feed_enabled", "true"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.header_bg_color2", "0c91c3"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.public_company_name", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.notification_email", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.email_notification_template", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.teams_notifications_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.status_maintenance_color", "5378c1"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.email_confirmation_template", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.time_zone", "Europe/Belgrade"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.calendar_enabled", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.major_notification_hours", "3"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.incident_header_color", "009688"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.reply_to_email", ""),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.noindex", "false"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.inserted_at", "2024-04-15T11:20:35"),
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "status_pages.0.updated_at", "2024-04-20T11:22:32"),
					// Verify placeholder id attribute
					resource.TestCheckResourceAttr("data.statuspal_status_pages.test", "id", "placeholder"),
				),
			},
		},
	})
}
